"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express = require('express');
var cors = require('cors');
var CORS_1 = require("./middleware/CORS");
//import { loggingMiddleware } from './middleware/loggingMiddleware';
var tokenExtractor_1 = require("./middleware/tokenExtractor");
var DatabaseNameGen_1 = require("./middleware/DatabaseNameGen");
var ConnectToClientListMiddleware_1 = require("./middleware/ConnectToClientListMiddleware");
var AuthenticateUserMiddleware_1 = require("./middleware/AuthenticateUserMiddleware");
var AddClientToListMiddleware_1 = require("./middleware/AddClientToListMiddleware");
var DisconnectListOfClientsMiddleware_1 = require("./middleware/DisconnectListOfClientsMiddleware");
var expressAppRouter_1 = require("./routes/expressAppRouter");
require('dotenv').config();
var app = express();
console.log('created app instance');
// app.options('*', (req: any, res: any) => {
//     res.header('Access-Control-Allow-Origin', 'http://localhost:3000');
//     res.header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE');
//     res.header('Access-Control-Allow-Headers', 'Content-Type, Authorization');
//     res.header('Access-Control-Allow-Credentials', 'true');
//     res.status(204).end();
// });
app.use(cors(CORS_1.corsConfig));
console.log('took update7.');
app.use(express.json());
//app.use(loggingMiddleware);
app.use(ConnectToClientListMiddleware_1.ConnectToClientListMiddleWare);
app.use(DatabaseNameGen_1.DatabaseNameGen);
app.use(AddClientToListMiddleware_1.AddClientToListMiddleware);
app.use(AuthenticateUserMiddleware_1.AuthenicateUserMiddleware);
app.use(tokenExtractor_1.tokenExtractor);
app.use(DisconnectListOfClientsMiddleware_1.DisconnectFromClientList);
app.get('/', function (req, res) {
    res.send('Hello, this is the root path!');
});
app.use('/', expressAppRouter_1.default);
var PORT = process.env.PORT || 3001;
app.listen(PORT, function () {
    console.log("Server is running on http://localhost:".concat(PORT));
});
module.exports = app;
